# Generated by Django 4.2.1 on 2023-08-07 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.ram.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Corsair', 'Corsair'), ('Kingston', 'Kingston'), ('G.Skill', 'G.Skill'), ('Crucial', 'Crucial'), ('Samsung', 'Samsung'), ('ADATA', 'ADATA'), ('HyperX', 'HyperX'), ('Patriot', 'Patriot'), ('Silicon Power', 'Silicon Power')], max_length=20)),
                ('memory_type', models.CharField(choices=[('DDR1', 'DDR1'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10, verbose_name='Memory type (DDR)')),
                ('speed', models.CharField(choices=[('200', '200 MHz'), ('266', '266 MHz'), ('333', '333 MHz'), ('400', '400 MHz'), ('533', '533 MHz'), ('667', '667 MHz'), ('800', '800 MHz'), ('1000', '1000 MHz'), ('1066', '1066 MHz'), ('1333', '1333 MHz'), ('1600', '1600 MHz'), ('1866', '1866 MHz'), ('2133', '2133 MHz'), ('2400', '2400 MHz'), ('2666', '2666 MHz'), ('2933', '2933 MHz'), ('3200', '3200 MHz'), ('3600', '3600 MHz'), ('4000', '4000 MHz'), ('4400', '4400 MHz'), ('4800', '4800 MHz'), ('5200', '5200 MHz'), ('5600', '5600 MHz')], max_length=20)),
                ('capacity', models.PositiveIntegerField(validators=[project.ram.validators.capacity_validator], verbose_name='Memory capacity (GB)')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RAM',
            },
        ),
    ]
