# Generated by Django 4.2.1 on 2023-07-04 18:22

from django.db import migrations, models
import project.ram.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('memory_type', models.CharField(choices=[('DDR1', 'DDR1'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10, verbose_name='Memory type (DDR)')),
                ('speed', models.CharField(choices=[], max_length=20)),
                ('capacity', models.PositiveIntegerField(validators=[project.ram.validators.capacity_validator], verbose_name='Memory capacity (GB)')),
            ],
        ),
    ]
