# Generated by Django 4.2.1 on 2023-07-04 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Memory capacity (GB)'),
        ),
    ]
