# Generated by Django 4.2.1 on 2023-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='brand',
            field=models.CharField(choices=[('Corsair', 'Corsair'), ('Kingston', 'Kingston'), ('G.Skill', 'G.Skill'), ('Crucial', 'Crucial'), ('Samsung', 'Samsung'), ('ADATA', 'ADATA'), ('HyperX', 'HyperX'), ('Patriot', 'Patriot'), ('Silicon Power', 'Silicon Power')], max_length=20),
        ),
    ]
