# Generated by Django 4.2.1 on 2023-08-07 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motherboards', '0001_initial'),
        ('storage', '0001_initial'),
        ('cpus', '0001_initial'),
        ('ram', '0001_initial'),
        ('gpus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpus.chosencpus', verbose_name='CPU')),
                ('choose_gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpus.chosengpus', verbose_name='GPU')),
                ('choose_motherboards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motherboards.motherboard', verbose_name='Motherboard')),
                ('choose_ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ram.ram', verbose_name='RAM')),
                ('choose_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage', verbose_name='Storage')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_pcs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Show PCs',
            },
        ),
    ]
