# Generated by Django 4.2.1 on 2023-07-15 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0002_alter_storage_capacity'),
        ('motherboards', '0001_initial'),
        ('gpus', '0002_alter_allgpus_memory_size'),
        ('ram', '0002_alter_ram_brand'),
        ('cpus', '0004_alter_allcpus_threads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpus.chosencpus')),
                ('choose_gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpus.chosengpus')),
                ('choose_motherboards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motherboards.motherboard')),
                ('choose_ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ram.ram')),
                ('choose_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_pcs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
