# Generated by Django 4.2.1 on 2023-07-12 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpus', '0004_alter_allcpus_threads'),
        ('common', '0002_alter_showpc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showpc',
            name='choose_cpu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpus.chosencpus'),
        ),
        migrations.AlterField(
            model_name='showpc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
