# Generated by Django 4.2.1 on 2023-07-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0004_alter_allcpus_threads'),
        ('common', '0003_alter_showpc_choose_cpu_alter_showpc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showpc',
            name='choose_cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpus.chosencpus'),
        ),
        migrations.AlterField(
            model_name='showpc',
            name='user',
            field=models.CharField(max_length=156),
        ),
    ]
