# Generated by Django 4.2.1 on 2023-07-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
