# Generated by Django 4.2.1 on 2023-07-13 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0009_like_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpc',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_pcs', to=settings.AUTH_USER_MODEL),
        ),
    ]
