# Generated by Django 4.2.1 on 2023-07-09 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100, 'Capacity should be bigger than 100!')], verbose_name='Capacity'),
        ),
    ]
