# Generated by Django 4.2.1 on 2023-07-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgpus',
            name='memory_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Memory size'),
        ),
    ]
