# Generated by Django 4.2.1 on 2023-08-07 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.cpus.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('AMD', 'AMD'), ('Intel', 'Intel')], max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cores', models.PositiveIntegerField(blank=True, null=True)),
                ('threads', models.PositiveIntegerField(blank=True, null=True)),
                ('max_turbo_frequency', models.FloatField(blank=True, null=True)),
                ('base_frequency', models.FloatField(blank=True, null=True)),
                ('tdp', models.PositiveIntegerField(blank=True, null=True)),
                ('cache', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[project.cpus.validators.cpu_name_validator])),
                ('manufacturer', models.CharField(max_length=30)),
                ('clock_speed', models.DecimalField(decimal_places=2, max_digits=4, validators=[project.cpus.validators.cpu_clock_speed_validator])),
                ('number_of_cores', models.PositiveIntegerField(validators=[project.cpus.validators.cpu_number_cores_validator])),
                ('cache_size', models.PositiveIntegerField(validators=[project.cpus.validators.cpu_cache_size_validator])),
                ('max_ram', models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ChosenCpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_custom_cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpus.customcpu')),
                ('chosen_cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpus.allcpus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chosen CPUs',
            },
        ),
    ]
