# Generated by Django 4.2.1 on 2023-06-28 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('AMD', 'AMD'), ('Intel', 'Intel')], max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cores', models.IntegerField(blank=True, null=True, verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('threads', models.IntegerField(blank=True, null=True)),
                ('max_turbo_frequency', models.FloatField(blank=True, null=True)),
                ('base_turbo_frequency', models.FloatField(blank=True, null=True)),
                ('tdp', models.CharField(blank=True, max_length=15, null=True)),
                ('cache', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
