# Generated by Django 4.2.1 on 2023-07-01 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, choices=[('AMD', 'AMD'), ('Intel', 'Intel')], max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cores', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('threads', models.IntegerField(blank=True, null=True)),
                ('base_frequency', models.FloatField(blank=True, null=True)),
                ('max_turbo_frequency', models.FloatField(blank=True, null=True)),
                ('tdp', models.CharField(blank=True, max_length=15, null=True)),
                ('cache', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5, 'CPU name should be at least 5 characters long!')])),
                ('manufacturer', models.CharField(max_length=30)),
                ('clock_speed', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1, 'Clock speed should be bigger than 0!')])),
                ('number_of_cores', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Choose cores between 1 and 512!'), django.core.validators.MaxValueValidator(512, 'Choose cores between 1 and 512!')])),
                ('cache_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Choose cache size between 1 and 1024(MB)!'), django.core.validators.MaxValueValidator(1024, 'Choose cache size between 1 and 1024(MB)!')])),
                ('max_ram', models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], verbose_name='Max RAM')),
            ],
        ),
        migrations.CreateModel(
            name='ChosenCpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_custom_cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpus.customcpu')),
                ('chosen_cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpus.allcpus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
