# Generated by Django 4.2.1 on 2023-06-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcpus',
            old_name='base_turbo_frequency',
            new_name='base_frequency',
        ),
    ]
