# Generated by Django 4.2.1 on 2023-07-07 09:35

from django.db import migrations, models
import project.cpus.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0002_alter_customcpu_max_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcpu',
            name='cache_size',
            field=models.PositiveIntegerField(validators=[project.cpus.validators.cpu_cache_size_validator]),
        ),
        migrations.AlterField(
            model_name='customcpu',
            name='clock_speed',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[project.cpus.validators.cpu_clock_speed_validator]),
        ),
        migrations.AlterField(
            model_name='customcpu',
            name='name',
            field=models.CharField(max_length=30, validators=[project.cpus.validators.cpu_name_validator]),
        ),
        migrations.AlterField(
            model_name='customcpu',
            name='number_of_cores',
            field=models.PositiveIntegerField(validators=[project.cpus.validators.cpu_number_cores_validator]),
        ),
    ]
