# Generated by Django 4.2.1 on 2023-06-28 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0002_rename_base_turbo_frequency_allcpus_base_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcpus',
            name='cores',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)]),
        ),
    ]
