# Generated by Django 4.2.1 on 2023-07-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0003_alter_customcpu_cache_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcpus',
            name='threads',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
