# Generated by Django 4.2.1 on 2023-06-28 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0003_alter_allcpus_cores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcpus',
            name='cores',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'asd'), django.core.validators.MaxValueValidator(128)]),
        ),
    ]
