# Generated by Django 4.2.1 on 2023-06-28 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpus', '0004_alter_allcpus_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcpus',
            name='chosen_pc_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
