# Generated by Django 4.2.1 on 2023-06-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0005_allcpus_chosen_pc_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcpus',
            name='chosen_pc_by_user',
        ),
    ]
