# Generated by Django 4.2.1 on 2023-06-28 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpus', '0007_chosencpu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChosenCpu',
            new_name='ChosenCpus',
        ),
    ]
