# Generated by Django 4.2.1 on 2023-06-29 08:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0008_rename_chosencpu_chosencpus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('clock_speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('number_of_cores', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)])),
                ('cache_size', models.PositiveIntegerField()),
                ('max_ram', models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')])),
            ],
        ),
        migrations.RenameField(
            model_name='chosencpus',
            old_name='cpu',
            new_name='chosen_cpu',
        ),
        migrations.AddField(
            model_name='chosencpus',
            name='build_custom_cpu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cpus.customcpu'),
            preserve_default=False,
        ),
    ]
