# Generated by Django 4.2.1 on 2023-06-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0009_customcpu_rename_cpu_chosencpus_chosen_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosencpus',
            name='build_custom_cpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpus.customcpu'),
        ),
        migrations.AlterField(
            model_name='chosencpus',
            name='chosen_cpu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpus.allcpus'),
        ),
    ]
