# Generated by Django 4.2.1 on 2023-06-29 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0010_alter_chosencpus_build_custom_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcpu',
            name='number_of_cores',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)]),
        ),
    ]
