# Generated by Django 4.2.1 on 2023-06-29 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0011_alter_customcpu_number_of_cores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcpu',
            name='cache_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Choose cache size between 1 and 1024MB!'), django.core.validators.MaxValueValidator(1024, 'Choose cache size between 1 and 1024MB!')]),
        ),
        migrations.AlterField(
            model_name='customcpu',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5, 'CPU name should be at least 5 characters long!')]),
        ),
        migrations.AlterField(
            model_name='customcpu',
            name='number_of_cores',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Choose cores between 1 and 512!'), django.core.validators.MaxValueValidator(512, 'Choose cores between 1 and 512!')]),
        ),
    ]
