# Generated by Django 4.2.1 on 2023-06-29 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0012_alter_customcpu_cache_size_alter_customcpu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcpus',
            name='cores',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)]),
        ),
    ]
