# Generated by Django 4.2.1 on 2023-06-30 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0014_alter_customcpu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcpu',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5, 'CPU name should be at least 5 characters long!')]),
        ),
    ]
