# Generated by Django 4.2.1 on 2023-06-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0015_alter_customcpu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcpu',
            name='max_ram',
            field=models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], verbose_name='Max RAM'),
        ),
    ]
