# Generated by Django 4.2.1 on 2023-06-30 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0016_alter_customcpu_max_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcpu',
            name='cache_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Choose cache size between 1 and 1024(MB)!'), django.core.validators.MaxValueValidator(1024, 'Choose cache size between 1 and 1024(MB)!')]),
        ),
    ]
