# Generated by Django 4.2.1 on 2023-06-30 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpus', '0017_alter_customcpu_cache_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcpu',
            name='clock_speed',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.1, 'Clock speed should be bigger than 0!')]),
        ),
    ]
